# Generated by Django 4.2.1 on 2023-05-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medication", "0001_initial"),
        ("drones", "0002_drone_created_at_drone_updated_at_batterystatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Load",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drone_load",
                        to="drones.drone",
                    ),
                ),
                (
                    "payload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drone_payload",
                        to="medication.medicine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Load",
                "verbose_name_plural": "Loads",
                "db_table": "loads",
            },
        ),
        migrations.CreateModel(
            name="LoadStatusMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("loading", "Loading"),
                            ("loaded", "Loaded"),
                            ("delivering", "Delivering"),
                            ("delivered", "Delivered"),
                            ("returning", "Returning"),
                        ],
                        default="idle",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "load",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="load_status",
                        to="loads.load",
                    ),
                ),
            ],
            options={
                "verbose_name": "Load Status Movement",
                "verbose_name_plural": "Load Status Movements",
                "db_table": "load_status_movement",
            },
        ),
    ]
