# Generated by Django 4.2.1 on 2023-05-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("lightweight", "Lightweight"),
                            ("middleweight", "Middleweight"),
                            ("cruiserweight", "Cruiserweight"),
                            ("heavyweight", "Heavyweight"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("loading", "Loading"),
                            ("loaded", "Loaded"),
                            ("delivering", "Delivering"),
                            ("delivered", "Delivered"),
                            ("returning", "Returning"),
                        ],
                        max_length=15,
                    ),
                ),
                ("weight_limit", models.DecimalField(decimal_places=2, max_digits=5)),
                ("battery_capacity", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Drone",
                "verbose_name_plural": "Drones",
                "db_table": "drones",
            },
        ),
    ]
