# Generated by Django 4.2.1 on 2023-05-31 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0002_drone_created_at_drone_updated_at_batterystatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="state",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("loading", "Loading"),
                    ("loaded", "Loaded"),
                    ("delivering", "Delivering"),
                    ("delivered", "Delivered"),
                    ("returning", "Returning"),
                ],
                default="idle",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="DroneStatusMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("loading", "Loading"),
                            ("loaded", "Loaded"),
                            ("delivering", "Delivering"),
                            ("delivered", "Delivered"),
                            ("returning", "Returning"),
                        ],
                        default="idle",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drone_status_movement",
                        to="drones.drone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drone Status Movement",
                "verbose_name_plural": "Drone Status Movement",
                "db_table": "drone_status_movement",
            },
        ),
    ]
